//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubRenderer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_si {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_si() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SubRenderer.Resources.Resources_si", typeof(Resources_si).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; ආපසු.
        /// </summary>
        internal static string btnBack {
            get {
                return ResourceManager.GetString("btnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to තෝරන්න....
        /// </summary>
        internal static string btnBrowse {
            get {
                return ResourceManager.GetString("btnBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ඉවත් වන්න.
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to හරි.
        /// </summary>
        internal static string btnFinish {
            get {
                return ResourceManager.GetString("btnFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to මීලඟ &gt;.
        /// </summary>
        internal static string btnNext {
            get {
                return ResourceManager.GetString("btnNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to දාරයේ පැහැය.
        /// </summary>
        internal static string lblBorderCol {
            get {
                return ResourceManager.GetString("lblBorderCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to දාරයේ පළල.
        /// </summary>
        internal static string lblBorderSize {
            get {
                return ResourceManager.GetString("lblBorderSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to යොදාගතයුතු Cores ප්‍රමාණය.
        /// </summary>
        internal static string lblCores {
            get {
                return ResourceManager.GetString("lblCores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to අකුරු වර්ගය.
        /// </summary>
        internal static string lblFont {
            get {
                return ResourceManager.GetString("lblFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to අකුරු පැහැය.
        /// </summary>
        internal static string lblFontCol {
            get {
                return ResourceManager.GetString("lblFontCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to අකුරු ප්‍රමාණය.
        /// </summary>
        internal static string lblFontSize {
            get {
                return ResourceManager.GetString("lblFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FPS.
        /// </summary>
        internal static string lblFPS {
            get {
                return ResourceManager.GetString("lblFPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ක් පින්තූර සැකසුවා!.
        /// </summary>
        internal static string lblImagesRendered {
            get {
                return ResourceManager.GetString("lblImagesRendered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to උපසිරැසි ගොනුව.
        /// </summary>
        internal static string lblInputSub {
            get {
                return ResourceManager.GetString("lblInputSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to වීඩියෝ ගොනුව.
        /// </summary>
        internal static string lblInputVideo {
            get {
                return ResourceManager.GetString("lblInputVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to කරුණාකර රැදී සිටින්න....
        /// </summary>
        internal static string lblPleaseWait {
            get {
                return ResourceManager.GetString("lblPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to පිහිටීම.
        /// </summary>
        internal static string lblPosition {
            get {
                return ResourceManager.GetString("lblPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to පූර්වදර්ශනය.
        /// </summary>
        internal static string lblPreview {
            get {
                return ResourceManager.GetString("lblPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to උපසිරැසි ගුණාත්මක භාවය.
        /// </summary>
        internal static string lblSubQuality {
            get {
                return ResourceManager.GetString("lblSubQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ගැන.
        /// </summary>
        internal static string mnuAbout {
            get {
                return ResourceManager.GetString("mnuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ඉවත් වන්න.
        /// </summary>
        internal static string mnuExit {
            get {
                return ResourceManager.GetString("mnuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ගොනු.
        /// </summary>
        internal static string mnuFile {
            get {
                return ResourceManager.GetString("mnuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to උදව්.
        /// </summary>
        internal static string mnuHelp {
            get {
                return ResourceManager.GetString("mnuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to භාෂාව.
        /// </summary>
        internal static string mnuLanguage {
            get {
                return ResourceManager.GetString("mnuLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to උපසිරැසි ගොනුවක් විවෘත්ත කරන්න.
        /// </summary>
        internal static string mnuOepnSub {
            get {
                return ResourceManager.GetString("mnuOepnSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to වීඩියෝ ගොනුවක් විවෘත්ත කරන්න.
        /// </summary>
        internal static string mnuOpenVideo {
            get {
                return ResourceManager.GetString("mnuOpenVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to සුරැකිය යතු ස්ථානය.
        /// </summary>
        internal static string mnuOutputDir {
            get {
                return ResourceManager.GetString("mnuOutputDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to පරිවර්තනය ආරම්භ කරන්න.
        /// </summary>
        internal static string mnuRender {
            get {
                return ResourceManager.GetString("mnuRender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ඔබට විශ්වාස ද?.
        /// </summary>
        internal static string msgAreYouSure {
            get {
                return ResourceManager.GetString("msgAreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ඉවත් වන්න.
        /// </summary>
        internal static string msgCancel {
            get {
                return ResourceManager.GetString("msgCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to හරි.
        /// </summary>
        internal static string msgDone {
            get {
                return ResourceManager.GetString("msgDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to දෝෂයක්.
        /// </summary>
        internal static string msgError {
            get {
                return ResourceManager.GetString("msgError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to කරුණාකර සුරැකීමට ස්ථානයක් තෝරා දෙන්න!.
        /// </summary>
        internal static string msgErrorOutput {
            get {
                return ResourceManager.GetString("msgErrorOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to කරුණාකර උපසිරැසි ගොනුවක් විවෘත්ත කරන්න!.
        /// </summary>
        internal static string msgErrorSub {
            get {
                return ResourceManager.GetString("msgErrorSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to වීඩියෝ ගොනුව සකසමින්....
        /// </summary>
        internal static string msgMkv {
            get {
                return ResourceManager.GetString("msgMkv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to සාර්ථකව පරිවර්තනය කරන ලදි!.
        /// </summary>
        internal static string msgSuccess {
            get {
                return ResourceManager.GetString("msgSuccess", resourceCulture);
            }
        }
    }
}
