//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubRenderer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_ta {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_ta() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SubRenderer.Resources.Resources_ta", typeof(Resources_ta).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; மீண்டும்.
        /// </summary>
        internal static string btnBack {
            get {
                return ResourceManager.GetString("btnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to தேர்வு செய்....
        /// </summary>
        internal static string btnBrowse {
            get {
                return ResourceManager.GetString("btnBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to அகற்று.
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to முடிந்தது.
        /// </summary>
        internal static string btnFinish {
            get {
                return ResourceManager.GetString("btnFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to அடுத்து &gt;.
        /// </summary>
        internal static string btnNext {
            get {
                return ResourceManager.GetString("btnNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to போடர் நிறம்.
        /// </summary>
        internal static string lblBorderCol {
            get {
                return ResourceManager.GetString("lblBorderCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to போடர் அளவு.
        /// </summary>
        internal static string lblBorderSize {
            get {
                return ResourceManager.GetString("lblBorderSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to பயன்படுத்த வேண்டிய Cores எண்ணிக்கை.
        /// </summary>
        internal static string lblCores {
            get {
                return ResourceManager.GetString("lblCores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to எழுத்து வகை.
        /// </summary>
        internal static string lblFont {
            get {
                return ResourceManager.GetString("lblFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to எழுத்து நிறம்.
        /// </summary>
        internal static string lblFontCol {
            get {
                return ResourceManager.GetString("lblFontCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to எழுத்து அளவு.
        /// </summary>
        internal static string lblFontSize {
            get {
                return ResourceManager.GetString("lblFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FPS.
        /// </summary>
        internal static string lblFPS {
            get {
                return ResourceManager.GetString("lblFPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to உருவாக்கப்பட்ட படங்கள்.
        /// </summary>
        internal static string lblImagesRendered {
            get {
                return ResourceManager.GetString("lblImagesRendered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to உபதலைப்பு  கோப்பு.
        /// </summary>
        internal static string lblInputSub {
            get {
                return ResourceManager.GetString("lblInputSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to வீடியோ கோப்பு.
        /// </summary>
        internal static string lblInputVideo {
            get {
                return ResourceManager.GetString("lblInputVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to காத்திரு....
        /// </summary>
        internal static string lblPleaseWait {
            get {
                return ResourceManager.GetString("lblPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to அமைவு.
        /// </summary>
        internal static string lblPosition {
            get {
                return ResourceManager.GetString("lblPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to முந்தையது.
        /// </summary>
        internal static string lblPreview {
            get {
                return ResourceManager.GetString("lblPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to உபதையப்புக்கான தரம்.
        /// </summary>
        internal static string lblSubQuality {
            get {
                return ResourceManager.GetString("lblSubQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to பற்றி.
        /// </summary>
        internal static string mnuAbout {
            get {
                return ResourceManager.GetString("mnuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to வெளியேறு.
        /// </summary>
        internal static string mnuExit {
            get {
                return ResourceManager.GetString("mnuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to கோப்பு.
        /// </summary>
        internal static string mnuFile {
            get {
                return ResourceManager.GetString("mnuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to உதவி.
        /// </summary>
        internal static string mnuHelp {
            get {
                return ResourceManager.GetString("mnuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to மொழி.
        /// </summary>
        internal static string mnuLanguage {
            get {
                return ResourceManager.GetString("mnuLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to உபதலைப்பு கோப்பை திற.
        /// </summary>
        internal static string mnuOepnSub {
            get {
                return ResourceManager.GetString("mnuOepnSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to வீடியோவை திற.
        /// </summary>
        internal static string mnuOpenVideo {
            get {
                return ResourceManager.GetString("mnuOpenVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to சேமிக்க வேண்டிய இடம்.
        /// </summary>
        internal static string mnuOutputDir {
            get {
                return ResourceManager.GetString("mnuOutputDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to உபதலைப்பு மாற்றம் ஆரம்பமாகிறது.
        /// </summary>
        internal static string mnuRender {
            get {
                return ResourceManager.GetString("mnuRender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to உறுதி படுத்திகின்றீர்களா?.
        /// </summary>
        internal static string msgAreYouSure {
            get {
                return ResourceManager.GetString("msgAreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to இரத்து செய்.
        /// </summary>
        internal static string msgCancel {
            get {
                return ResourceManager.GetString("msgCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to முடிந்தது.
        /// </summary>
        internal static string msgDone {
            get {
                return ResourceManager.GetString("msgDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to பிழைகள் உள்ளது.
        /// </summary>
        internal static string msgError {
            get {
                return ResourceManager.GetString("msgError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to தயவு செய்து சேமிக்கும் இடத்தை தெரிவு செய்க!.
        /// </summary>
        internal static string msgErrorOutput {
            get {
                return ResourceManager.GetString("msgErrorOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to தயவு செய்து உபதலைப்பு கோப்பை தெரிவு செய்க!.
        /// </summary>
        internal static string msgErrorSub {
            get {
                return ResourceManager.GetString("msgErrorSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to வீடியோ கோப்பு தயாராகிறது....
        /// </summary>
        internal static string msgMkv {
            get {
                return ResourceManager.GetString("msgMkv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to வெற்றிகரமாக  மாற்றப்ப்டது!.
        /// </summary>
        internal static string msgSuccess {
            get {
                return ResourceManager.GetString("msgSuccess", resourceCulture);
            }
        }
    }
}
